// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: autotest.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckAttemptResponse_Grade int32

const (
	CheckAttemptResponse_EXCELLENT      CheckAttemptResponse_Grade = 0
	CheckAttemptResponse_GOOD           CheckAttemptResponse_Grade = 1
	CheckAttemptResponse_SATISFACTORY   CheckAttemptResponse_Grade = 2
	CheckAttemptResponse_UNSATISFACTORY CheckAttemptResponse_Grade = 3
	CheckAttemptResponse_NO_GRADE       CheckAttemptResponse_Grade = 4
)

// Enum value maps for CheckAttemptResponse_Grade.
var (
	CheckAttemptResponse_Grade_name = map[int32]string{
		0: "EXCELLENT",
		1: "GOOD",
		2: "SATISFACTORY",
		3: "UNSATISFACTORY",
		4: "NO_GRADE",
	}
	CheckAttemptResponse_Grade_value = map[string]int32{
		"EXCELLENT":      0,
		"GOOD":           1,
		"SATISFACTORY":   2,
		"UNSATISFACTORY": 3,
		"NO_GRADE":       4,
	}
)

func (x CheckAttemptResponse_Grade) Enum() *CheckAttemptResponse_Grade {
	p := new(CheckAttemptResponse_Grade)
	*p = x
	return p
}

func (x CheckAttemptResponse_Grade) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckAttemptResponse_Grade) Descriptor() protoreflect.EnumDescriptor {
	return file_autotest_proto_enumTypes[0].Descriptor()
}

func (CheckAttemptResponse_Grade) Type() protoreflect.EnumType {
	return &file_autotest_proto_enumTypes[0]
}

func (x CheckAttemptResponse_Grade) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckAttemptResponse_Grade.Descriptor instead.
func (CheckAttemptResponse_Grade) EnumDescriptor() ([]byte, []int) {
	return file_autotest_proto_rawDescGZIP(), []int{3, 0}
}

type CheckAttemptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TestPoints []*TestPoint `protobuf:"bytes,1,rep,name=test_points,json=testPoints,proto3" json:"test_points,omitempty"`
	GradeScale *GradeScale  `protobuf:"bytes,2,opt,name=grade_scale,json=gradeScale,proto3" json:"grade_scale,omitempty"`
}

func (x *CheckAttemptRequest) Reset() {
	*x = CheckAttemptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_autotest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAttemptRequest) ProtoMessage() {}

func (x *CheckAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autotest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAttemptRequest.ProtoReflect.Descriptor instead.
func (*CheckAttemptRequest) Descriptor() ([]byte, []int) {
	return file_autotest_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAttemptRequest) GetTestPoints() []*TestPoint {
	if x != nil {
		return x.TestPoints
	}
	return nil
}

func (x *CheckAttemptRequest) GetGradeScale() *GradeScale {
	if x != nil {
		return x.GradeScale
	}
	return nil
}

type TestPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrectVariantNumbers []int32 `protobuf:"varint,1,rep,packed,name=correct_variant_numbers,json=correctVariantNumbers,proto3" json:"correct_variant_numbers,omitempty"`
	ChosenVariantNumbers  []int32 `protobuf:"varint,2,rep,packed,name=chosen_variant_numbers,json=chosenVariantNumbers,proto3" json:"chosen_variant_numbers,omitempty"`
}

func (x *TestPoint) Reset() {
	*x = TestPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_autotest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPoint) ProtoMessage() {}

func (x *TestPoint) ProtoReflect() protoreflect.Message {
	mi := &file_autotest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPoint.ProtoReflect.Descriptor instead.
func (*TestPoint) Descriptor() ([]byte, []int) {
	return file_autotest_proto_rawDescGZIP(), []int{1}
}

func (x *TestPoint) GetCorrectVariantNumbers() []int32 {
	if x != nil {
		return x.CorrectVariantNumbers
	}
	return nil
}

func (x *TestPoint) GetChosenVariantNumbers() []int32 {
	if x != nil {
		return x.ChosenVariantNumbers
	}
	return nil
}

type GradeScale struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExcellentLowerBound    int32 `protobuf:"varint,1,opt,name=excellent_lower_bound,json=excellentLowerBound,proto3" json:"excellent_lower_bound,omitempty"`
	GoodLowerBound         int32 `protobuf:"varint,2,opt,name=good_lower_bound,json=goodLowerBound,proto3" json:"good_lower_bound,omitempty"`
	SatisfactoryLowerBound int32 `protobuf:"varint,3,opt,name=satisfactory_lower_bound,json=satisfactoryLowerBound,proto3" json:"satisfactory_lower_bound,omitempty"`
}

func (x *GradeScale) Reset() {
	*x = GradeScale{}
	if protoimpl.UnsafeEnabled {
		mi := &file_autotest_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GradeScale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeScale) ProtoMessage() {}

func (x *GradeScale) ProtoReflect() protoreflect.Message {
	mi := &file_autotest_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeScale.ProtoReflect.Descriptor instead.
func (*GradeScale) Descriptor() ([]byte, []int) {
	return file_autotest_proto_rawDescGZIP(), []int{2}
}

func (x *GradeScale) GetExcellentLowerBound() int32 {
	if x != nil {
		return x.ExcellentLowerBound
	}
	return 0
}

func (x *GradeScale) GetGoodLowerBound() int32 {
	if x != nil {
		return x.GoodLowerBound
	}
	return 0
}

func (x *GradeScale) GetSatisfactoryLowerBound() int32 {
	if x != nil {
		return x.SatisfactoryLowerBound
	}
	return 0
}

type CheckAttemptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Grade   CheckAttemptResponse_Grade `protobuf:"varint,1,opt,name=grade,proto3,enum=autotest.CheckAttemptResponse_Grade" json:"grade,omitempty"`
	Percent int32                      `protobuf:"varint,2,opt,name=percent,proto3" json:"percent,omitempty"`
}

func (x *CheckAttemptResponse) Reset() {
	*x = CheckAttemptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_autotest_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckAttemptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAttemptResponse) ProtoMessage() {}

func (x *CheckAttemptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autotest_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAttemptResponse.ProtoReflect.Descriptor instead.
func (*CheckAttemptResponse) Descriptor() ([]byte, []int) {
	return file_autotest_proto_rawDescGZIP(), []int{3}
}

func (x *CheckAttemptResponse) GetGrade() CheckAttemptResponse_Grade {
	if x != nil {
		return x.Grade
	}
	return CheckAttemptResponse_EXCELLENT
}

func (x *CheckAttemptResponse) GetPercent() int32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

var File_autotest_proto protoreflect.FileDescriptor

var file_autotest_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x75, 0x74, 0x6f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x61, 0x75, 0x74, 0x6f, 0x74, 0x65, 0x73, 0x74, 0x22, 0x82, 0x01, 0x0a, 0x13, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x34, 0x0a, 0x0b, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0a, 0x74, 0x65,
	0x73, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x35, 0x0a, 0x0b, 0x67, 0x72, 0x61, 0x64,
	0x65, 0x5f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x61, 0x75, 0x74, 0x6f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x72, 0x61, 0x64, 0x65, 0x53, 0x63,
	0x61, 0x6c, 0x65, 0x52, 0x0a, 0x67, 0x72, 0x61, 0x64, 0x65, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x22,
	0x79, 0x0a, 0x09, 0x54, 0x65, 0x73, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x36, 0x0a, 0x17,
	0x63, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x15, 0x63,
	0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x12, 0x34, 0x0a, 0x16, 0x63, 0x68, 0x6f, 0x73, 0x65, 0x6e, 0x5f, 0x76,
	0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x14, 0x63, 0x68, 0x6f, 0x73, 0x65, 0x6e, 0x56, 0x61, 0x72, 0x69,
	0x61, 0x6e, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0xa4, 0x01, 0x0a, 0x0a, 0x47,
	0x72, 0x61, 0x64, 0x65, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x12, 0x32, 0x0a, 0x15, 0x65, 0x78, 0x63,
	0x65, 0x6c, 0x6c, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x62, 0x6f, 0x75,
	0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x13, 0x65, 0x78, 0x63, 0x65, 0x6c, 0x6c,
	0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x77, 0x65, 0x72, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x28, 0x0a,
	0x10, 0x67, 0x6f, 0x6f, 0x64, 0x5f, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x62, 0x6f, 0x75, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x67, 0x6f, 0x6f, 0x64, 0x4c, 0x6f, 0x77,
	0x65, 0x72, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x38, 0x0a, 0x18, 0x73, 0x61, 0x74, 0x69, 0x73,
	0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x62, 0x6f,
	0x75, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x16, 0x73, 0x61, 0x74, 0x69, 0x73,
	0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x4c, 0x6f, 0x77, 0x65, 0x72, 0x42, 0x6f, 0x75, 0x6e,
	0x64, 0x22, 0xc2, 0x01, 0x0a, 0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x74, 0x74, 0x65, 0x6d,
	0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x05, 0x67, 0x72,
	0x61, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x61, 0x75, 0x74, 0x6f,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x47, 0x72, 0x61, 0x64, 0x65, 0x52,
	0x05, 0x67, 0x72, 0x61, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x22, 0x54, 0x0a, 0x05, 0x47, 0x72, 0x61, 0x64, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x58, 0x43,
	0x45, 0x4c, 0x4c, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x4f, 0x4f, 0x44,
	0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x41, 0x54, 0x49, 0x53, 0x46, 0x41, 0x43, 0x54, 0x4f,
	0x52, 0x59, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x4e, 0x53, 0x41, 0x54, 0x49, 0x53, 0x46,
	0x41, 0x43, 0x54, 0x4f, 0x52, 0x59, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x5f, 0x47,
	0x52, 0x41, 0x44, 0x45, 0x10, 0x04, 0x32, 0x73, 0x0a, 0x0f, 0x41, 0x75, 0x74, 0x6f, 0x54, 0x65,
	0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x1d, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x54, 0x6f, 0x50, 0x61, 0x73, 0x73, 0x54,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x1d, 0x2e, 0x61, 0x75, 0x74,
	0x6f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x74, 0x74, 0x65, 0x6d,
	0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x75, 0x74, 0x6f,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x31, 0x5a, 0x2f, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x61, 0x2d, 0x72, 0x75, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x2d, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_autotest_proto_rawDescOnce sync.Once
	file_autotest_proto_rawDescData = file_autotest_proto_rawDesc
)

func file_autotest_proto_rawDescGZIP() []byte {
	file_autotest_proto_rawDescOnce.Do(func() {
		file_autotest_proto_rawDescData = protoimpl.X.CompressGZIP(file_autotest_proto_rawDescData)
	})
	return file_autotest_proto_rawDescData
}

var file_autotest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_autotest_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_autotest_proto_goTypes = []interface{}{
	(CheckAttemptResponse_Grade)(0), // 0: autotest.CheckAttemptResponse.Grade
	(*CheckAttemptRequest)(nil),     // 1: autotest.CheckAttemptRequest
	(*TestPoint)(nil),               // 2: autotest.TestPoint
	(*GradeScale)(nil),              // 3: autotest.GradeScale
	(*CheckAttemptResponse)(nil),    // 4: autotest.CheckAttemptResponse
}
var file_autotest_proto_depIdxs = []int32{
	2, // 0: autotest.CheckAttemptRequest.test_points:type_name -> autotest.TestPoint
	3, // 1: autotest.CheckAttemptRequest.grade_scale:type_name -> autotest.GradeScale
	0, // 2: autotest.CheckAttemptResponse.grade:type_name -> autotest.CheckAttemptResponse.Grade
	1, // 3: autotest.AutoTestService.CheckAttemptToPassTestingTask:input_type -> autotest.CheckAttemptRequest
	4, // 4: autotest.AutoTestService.CheckAttemptToPassTestingTask:output_type -> autotest.CheckAttemptResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_autotest_proto_init() }
func file_autotest_proto_init() {
	if File_autotest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_autotest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckAttemptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_autotest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_autotest_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GradeScale); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_autotest_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckAttemptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_autotest_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_autotest_proto_goTypes,
		DependencyIndexes: file_autotest_proto_depIdxs,
		EnumInfos:         file_autotest_proto_enumTypes,
		MessageInfos:      file_autotest_proto_msgTypes,
	}.Build()
	File_autotest_proto = out.File
	file_autotest_proto_rawDesc = nil
	file_autotest_proto_goTypes = nil
	file_autotest_proto_depIdxs = nil
}
